### ISSUE TITLE
Review by pretix author

### ISSUE THREAD

**Issue by lazyfrosch** [NETWAYS/pretix-invoice-net#2]
Have we talked to the main author of https://github.com/pretix/pretix about this? /cc @raphaelm

Main purpose of this plugin is to be conform with German invoice regulations.

These require:
* Quantity
* ~~Net and Gross declarations~~ (included upstream)

Since pretix is also targeted on the German market it would make sense to incorporate some of the changes upstream.

**Comment by raphaelm** [comment]
Hi @lazyfrosch! 

> Net and Gross declarations

pretix' regular invoices do have net and gross declarations for every line as well as for the total, or do I understand you wrong?

> Quantity

Are you sure? I don't have a source for it but I cannot really believe that the invoice is problematic without having a useless "1" in every line if all product names have singular names. It becomes even harder do misinterpret as soon as you turn on attendee names for each invoice line.

**Comment by lazyfrosch** [comment]
At least for the quantity we did check with our accountant, and it seems like it is a must, even when only 1 quantity exists.

I'm not 100% up to date on other changes we did to the invoice, the table borders are more of a custom addon :)

**Comment by raphaelm** [comment]
> At least for the quantity we did check with our accountant, and it seems like it is a must, even when only 1 quantity exists.

I'm still struggling to believe this, but it doesn't hurt to have it, I guess. Except for the precious horizontal space 😉 
https://github.com/pretix/pretix/commit/fb34467cba680e3d82c9340bac4b04a7633c4536

**Comment by bobapple** [comment]
@raphaelm thanks for you effort.

I'm closing this issue, since we're implementing some other changes to the invoices that are that are netways specific.

Anyways, thank you for making this software so great and open source!
